export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const GET_USER_INFO = "GET_USER_INFO";
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";
export const GET_USER_INFO_ERROR = "GET_USER_INFO_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_PROFILE = "CLEAR_PROFILE";

export const CLEAR_PROVERBS = "CLEAR_PROVERBS";

export const GET_PROVERBS = "GET_PROVERBS";
export const GET_PROVERBS_SUCCESS = "GET_PROVERBS_SUCCESS";
export const GET_PROVERBS_ERROR = "GET_PROVERBS_ERROR";

export const GET_USER_PROVERBS = "GET_USER_PROVERBS";
export const GET_USER_PROVERBS_SUCCESS = "GET_USER_PROVERBS_SUCCESS";
export const GET_USER_PROVERBS_ERROR = "GET_USER_PROVERBS_ERROR";

export const GET_PROVERB = "GET_PROVERB";
export const GET_PROVERB_SUCCESS = "GET_PROVERB_SUCCESS";
export const GET_PROVERB_ERROR = "GET_PROVERB_ERROR";

export const ADD_PROVERB = "ADD_PROVERB";
export const ADD_PROVERB_SUCCESS = "ADD_PROVERB_SUCCESS";
export const ADD_PROVERB_ERROR = "ADD_PROVERB_ERROR";

export const ADD_USER_PROVERB = "ADD_USER_PROVERB";
export const ADD_USER_PROVERB_SUCCESS = "ADD_USER_PROVERB_SUCCESS";
export const ADD_USER_PROVERB_ERROR = "ADD_USER_PROVERB_ERROR";

export const UPDATE_PROVERB = "UPDATE_PROVERB";
export const UPDATE_PROVERB_SUCCESS = "UPDATE_PROVERB_SUCCESS";
export const UPDATE_PROVERB_ERROR = "UPDATE_PROVERB_ERROR";

export const DELETE_PROVERB = "DELETE_PROVERB";
export const DELETE_PROVERB_SUCCESS = "DELETE_PROVERB_SUCCESS";
export const DELETE_PROVERB_ERROR = "DELETE_PROVERB_ERROR";
